# Generated by Django 4.2.11 on 2024-05-30 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_remove_education_program_remove_education_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='spesialized',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
