# Generated by Django 4.2.11 on 2024-05-30 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_identity_description_identity_spesialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documentation',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identity',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='identity',
            name='instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='identity',
            name='linkdin',
            field=models.URLField(),
        ),
    ]
