# Generated by Django 4.2.11 on 2024-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_identity_avatar_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='avatar',
            field=models.ImageField(upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='assets/'),
        ),
    ]
